version: "3.5"
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=startup_lanches      
      - MYSQL_PASSWORD=pass
    expose:
      - "3306"

  web:
    image: superlanches
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306   